# Generated by Django 4.1 on 2022-09-04 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursetheme",
            name="course",
        ),
        migrations.RemoveField(
            model_name="coursetheme",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="description",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="image",
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CourseTeacher",
        ),
        migrations.DeleteModel(
            name="CourseTheme",
        ),
    ]
